package com.xue.erp.datasource.mappers;

import com.xue.erp.datasource.entities.DepotHead;
import com.xue.erp.datasource.entities.DepotHeadExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DepotHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depothead
     *
     * @mbggenerated
     */
    int countByExample(DepotHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depothead
     *
     * @mbggenerated
     */
    int deleteByExample(DepotHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depothead
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depothead
     *
     * @mbggenerated
     */
    int insert(DepotHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depothead
     *
     * @mbggenerated
     */
    int insertSelective(DepotHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depothead
     *
     * @mbggenerated
     */
    List<DepotHead> selectByExample(DepotHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depothead
     *
     * @mbggenerated
     */
    DepotHead selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depothead
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DepotHead record, @Param("example") DepotHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depothead
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DepotHead record, @Param("example") DepotHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depothead
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DepotHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depothead
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DepotHead record);
}