package com.xue.erp.datasource.mappers;

import com.xue.erp.datasource.entities.InOutItem;
import com.xue.erp.datasource.entities.InOutItemExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface InOutItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inoutitem
     *
     * @mbggenerated
     */
    int countByExample(InOutItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inoutitem
     *
     * @mbggenerated
     */
    int deleteByExample(InOutItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inoutitem
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inoutitem
     *
     * @mbggenerated
     */
    int insert(InOutItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inoutitem
     *
     * @mbggenerated
     */
    int insertSelective(InOutItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inoutitem
     *
     * @mbggenerated
     */
    List<InOutItem> selectByExample(InOutItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inoutitem
     *
     * @mbggenerated
     */
    InOutItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inoutitem
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InOutItem record, @Param("example") InOutItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inoutitem
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InOutItem record, @Param("example") InOutItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inoutitem
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InOutItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inoutitem
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InOutItem record);
}