package com.xue.erp.datasource.mappers;

import com.xue.erp.datasource.entities.UserBusiness;
import com.xue.erp.datasource.entities.UserBusinessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbusiness
     *
     * @mbggenerated
     */
    int countByExample(UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbusiness
     *
     * @mbggenerated
     */
    int deleteByExample(UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbusiness
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbusiness
     *
     * @mbggenerated
     */
    int insert(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbusiness
     *
     * @mbggenerated
     */
    int insertSelective(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbusiness
     *
     * @mbggenerated
     */
    List<UserBusiness> selectByExample(UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbusiness
     *
     * @mbggenerated
     */
    UserBusiness selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbusiness
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserBusiness record, @Param("example") UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbusiness
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserBusiness record, @Param("example") UserBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbusiness
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbusiness
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserBusiness record);
}