package com.xue.erp.datasource.entities;

import java.math.BigDecimal;
import java.util.Date;

public class AccountHead {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounthead.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounthead.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounthead.OrganId
     *
     * @mbggenerated
     */
    private Long organid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounthead.HandsPersonId
     *
     * @mbggenerated
     */
    private Long handspersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounthead.ChangeAmount
     *
     * @mbggenerated
     */
    private BigDecimal changeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounthead.TotalPrice
     *
     * @mbggenerated
     */
    private BigDecimal totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounthead.AccountId
     *
     * @mbggenerated
     */
    private Long accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounthead.BillNo
     *
     * @mbggenerated
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounthead.BillTime
     *
     * @mbggenerated
     */
    private Date billtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounthead.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounthead.Id
     *
     * @return the value of accounthead.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounthead.Id
     *
     * @param id the value for accounthead.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounthead.Type
     *
     * @return the value of accounthead.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounthead.Type
     *
     * @param type the value for accounthead.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounthead.OrganId
     *
     * @return the value of accounthead.OrganId
     *
     * @mbggenerated
     */
    public Long getOrganid() {
        return organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounthead.OrganId
     *
     * @param organid the value for accounthead.OrganId
     *
     * @mbggenerated
     */
    public void setOrganid(Long organid) {
        this.organid = organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounthead.HandsPersonId
     *
     * @return the value of accounthead.HandsPersonId
     *
     * @mbggenerated
     */
    public Long getHandspersonid() {
        return handspersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounthead.HandsPersonId
     *
     * @param handspersonid the value for accounthead.HandsPersonId
     *
     * @mbggenerated
     */
    public void setHandspersonid(Long handspersonid) {
        this.handspersonid = handspersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounthead.ChangeAmount
     *
     * @return the value of accounthead.ChangeAmount
     *
     * @mbggenerated
     */
    public BigDecimal getChangeamount() {
        return changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounthead.ChangeAmount
     *
     * @param changeamount the value for accounthead.ChangeAmount
     *
     * @mbggenerated
     */
    public void setChangeamount(BigDecimal changeamount) {
        this.changeamount = changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounthead.TotalPrice
     *
     * @return the value of accounthead.TotalPrice
     *
     * @mbggenerated
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounthead.TotalPrice
     *
     * @param totalprice the value for accounthead.TotalPrice
     *
     * @mbggenerated
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounthead.AccountId
     *
     * @return the value of accounthead.AccountId
     *
     * @mbggenerated
     */
    public Long getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounthead.AccountId
     *
     * @param accountid the value for accounthead.AccountId
     *
     * @mbggenerated
     */
    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounthead.BillNo
     *
     * @return the value of accounthead.BillNo
     *
     * @mbggenerated
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounthead.BillNo
     *
     * @param billno the value for accounthead.BillNo
     *
     * @mbggenerated
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounthead.BillTime
     *
     * @return the value of accounthead.BillTime
     *
     * @mbggenerated
     */
    public Date getBilltime() {
        return billtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounthead.BillTime
     *
     * @param billtime the value for accounthead.BillTime
     *
     * @mbggenerated
     */
    public void setBilltime(Date billtime) {
        this.billtime = billtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounthead.Remark
     *
     * @return the value of accounthead.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounthead.Remark
     *
     * @param remark the value for accounthead.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}