package com.xue.erp.datasource.entities;

public class AssetName {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetname.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetname.assetname
     *
     * @mbggenerated
     */
    private String assetname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetname.assetcategoryID
     *
     * @mbggenerated
     */
    private Long assetcategoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetname.isystem
     *
     * @mbggenerated
     */
    private Short isystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetname.isconsumables
     *
     * @mbggenerated
     */
    private Short isconsumables;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assetname.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetname.id
     *
     * @return the value of assetname.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetname.id
     *
     * @param id the value for assetname.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetname.assetname
     *
     * @return the value of assetname.assetname
     *
     * @mbggenerated
     */
    public String getAssetname() {
        return assetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetname.assetname
     *
     * @param assetname the value for assetname.assetname
     *
     * @mbggenerated
     */
    public void setAssetname(String assetname) {
        this.assetname = assetname == null ? null : assetname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetname.assetcategoryID
     *
     * @return the value of assetname.assetcategoryID
     *
     * @mbggenerated
     */
    public Long getAssetcategoryid() {
        return assetcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetname.assetcategoryID
     *
     * @param assetcategoryid the value for assetname.assetcategoryID
     *
     * @mbggenerated
     */
    public void setAssetcategoryid(Long assetcategoryid) {
        this.assetcategoryid = assetcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetname.isystem
     *
     * @return the value of assetname.isystem
     *
     * @mbggenerated
     */
    public Short getIsystem() {
        return isystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetname.isystem
     *
     * @param isystem the value for assetname.isystem
     *
     * @mbggenerated
     */
    public void setIsystem(Short isystem) {
        this.isystem = isystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetname.isconsumables
     *
     * @return the value of assetname.isconsumables
     *
     * @mbggenerated
     */
    public Short getIsconsumables() {
        return isconsumables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetname.isconsumables
     *
     * @param isconsumables the value for assetname.isconsumables
     *
     * @mbggenerated
     */
    public void setIsconsumables(Short isconsumables) {
        this.isconsumables = isconsumables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assetname.description
     *
     * @return the value of assetname.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assetname.description
     *
     * @param description the value for assetname.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}