package com.xue.erp.datasource.entities;

import java.math.BigDecimal;
import java.util.Date;

public class Asset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.assetnameID
     *
     * @mbggenerated
     */
    private Long assetnameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.labels
     *
     * @mbggenerated
     */
    private String labels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.userID
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.purchasedate
     *
     * @mbggenerated
     */
    private Date purchasedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.periodofvalidity
     *
     * @mbggenerated
     */
    private Date periodofvalidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.warrantydate
     *
     * @mbggenerated
     */
    private Date warrantydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.assetnum
     *
     * @mbggenerated
     */
    private String assetnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.serialnum
     *
     * @mbggenerated
     */
    private String serialnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.supplier
     *
     * @mbggenerated
     */
    private Long supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.creator
     *
     * @mbggenerated
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.updator
     *
     * @mbggenerated
     */
    private Long updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.addMonth
     *
     * @mbggenerated
     */
    private String addmonth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.id
     *
     * @return the value of asset.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.id
     *
     * @param id the value for asset.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.assetnameID
     *
     * @return the value of asset.assetnameID
     *
     * @mbggenerated
     */
    public Long getAssetnameid() {
        return assetnameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.assetnameID
     *
     * @param assetnameid the value for asset.assetnameID
     *
     * @mbggenerated
     */
    public void setAssetnameid(Long assetnameid) {
        this.assetnameid = assetnameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.location
     *
     * @return the value of asset.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.location
     *
     * @param location the value for asset.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.labels
     *
     * @return the value of asset.labels
     *
     * @mbggenerated
     */
    public String getLabels() {
        return labels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.labels
     *
     * @param labels the value for asset.labels
     *
     * @mbggenerated
     */
    public void setLabels(String labels) {
        this.labels = labels == null ? null : labels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.status
     *
     * @return the value of asset.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.status
     *
     * @param status the value for asset.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.userID
     *
     * @return the value of asset.userID
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.userID
     *
     * @param userid the value for asset.userID
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.price
     *
     * @return the value of asset.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.price
     *
     * @param price the value for asset.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.purchasedate
     *
     * @return the value of asset.purchasedate
     *
     * @mbggenerated
     */
    public Date getPurchasedate() {
        return purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.purchasedate
     *
     * @param purchasedate the value for asset.purchasedate
     *
     * @mbggenerated
     */
    public void setPurchasedate(Date purchasedate) {
        this.purchasedate = purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.periodofvalidity
     *
     * @return the value of asset.periodofvalidity
     *
     * @mbggenerated
     */
    public Date getPeriodofvalidity() {
        return periodofvalidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.periodofvalidity
     *
     * @param periodofvalidity the value for asset.periodofvalidity
     *
     * @mbggenerated
     */
    public void setPeriodofvalidity(Date periodofvalidity) {
        this.periodofvalidity = periodofvalidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.warrantydate
     *
     * @return the value of asset.warrantydate
     *
     * @mbggenerated
     */
    public Date getWarrantydate() {
        return warrantydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.warrantydate
     *
     * @param warrantydate the value for asset.warrantydate
     *
     * @mbggenerated
     */
    public void setWarrantydate(Date warrantydate) {
        this.warrantydate = warrantydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.assetnum
     *
     * @return the value of asset.assetnum
     *
     * @mbggenerated
     */
    public String getAssetnum() {
        return assetnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.assetnum
     *
     * @param assetnum the value for asset.assetnum
     *
     * @mbggenerated
     */
    public void setAssetnum(String assetnum) {
        this.assetnum = assetnum == null ? null : assetnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.serialnum
     *
     * @return the value of asset.serialnum
     *
     * @mbggenerated
     */
    public String getSerialnum() {
        return serialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.serialnum
     *
     * @param serialnum the value for asset.serialnum
     *
     * @mbggenerated
     */
    public void setSerialnum(String serialnum) {
        this.serialnum = serialnum == null ? null : serialnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.supplier
     *
     * @return the value of asset.supplier
     *
     * @mbggenerated
     */
    public Long getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.supplier
     *
     * @param supplier the value for asset.supplier
     *
     * @mbggenerated
     */
    public void setSupplier(Long supplier) {
        this.supplier = supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.createtime
     *
     * @return the value of asset.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.createtime
     *
     * @param createtime the value for asset.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.creator
     *
     * @return the value of asset.creator
     *
     * @mbggenerated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.creator
     *
     * @param creator the value for asset.creator
     *
     * @mbggenerated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.updatetime
     *
     * @return the value of asset.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.updatetime
     *
     * @param updatetime the value for asset.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.updator
     *
     * @return the value of asset.updator
     *
     * @mbggenerated
     */
    public Long getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.updator
     *
     * @param updator the value for asset.updator
     *
     * @mbggenerated
     */
    public void setUpdator(Long updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.description
     *
     * @return the value of asset.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.description
     *
     * @param description the value for asset.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.addMonth
     *
     * @return the value of asset.addMonth
     *
     * @mbggenerated
     */
    public String getAddmonth() {
        return addmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.addMonth
     *
     * @param addmonth the value for asset.addMonth
     *
     * @mbggenerated
     */
    public void setAddmonth(String addmonth) {
        this.addmonth = addmonth == null ? null : addmonth.trim();
    }
}