package com.xue.erp.datasource.entities;

import java.math.BigDecimal;
import java.util.Date;

public class DepotHead {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.SubType
     *
     * @mbggenerated
     */
    private String subtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.ProjectId
     *
     * @mbggenerated
     */
    private Long projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.DefaultNumber
     *
     * @mbggenerated
     */
    private String defaultnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.Number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.OperPersonName
     *
     * @mbggenerated
     */
    private String operpersonname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.OperTime
     *
     * @mbggenerated
     */
    private Date opertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.OrganId
     *
     * @mbggenerated
     */
    private Long organid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.HandsPersonId
     *
     * @mbggenerated
     */
    private Long handspersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.AccountId
     *
     * @mbggenerated
     */
    private Long accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.ChangeAmount
     *
     * @mbggenerated
     */
    private BigDecimal changeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.AllocationProjectId
     *
     * @mbggenerated
     */
    private Long allocationprojectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.TotalPrice
     *
     * @mbggenerated
     */
    private BigDecimal totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.PayType
     *
     * @mbggenerated
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.Salesman
     *
     * @mbggenerated
     */
    private String salesman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.AccountIdList
     *
     * @mbggenerated
     */
    private String accountidlist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.AccountMoneyList
     *
     * @mbggenerated
     */
    private String accountmoneylist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.Discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.DiscountMoney
     *
     * @mbggenerated
     */
    private BigDecimal discountmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.DiscountLastMoney
     *
     * @mbggenerated
     */
    private BigDecimal discountlastmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.OtherMoney
     *
     * @mbggenerated
     */
    private BigDecimal othermoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.OtherMoneyList
     *
     * @mbggenerated
     */
    private String othermoneylist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.OtherMoneyItem
     *
     * @mbggenerated
     */
    private String othermoneyitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.AccountDay
     *
     * @mbggenerated
     */
    private Integer accountday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depothead.Status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.Id
     *
     * @return the value of depothead.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.Id
     *
     * @param id the value for depothead.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.Type
     *
     * @return the value of depothead.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.Type
     *
     * @param type the value for depothead.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.SubType
     *
     * @return the value of depothead.SubType
     *
     * @mbggenerated
     */
    public String getSubtype() {
        return subtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.SubType
     *
     * @param subtype the value for depothead.SubType
     *
     * @mbggenerated
     */
    public void setSubtype(String subtype) {
        this.subtype = subtype == null ? null : subtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.ProjectId
     *
     * @return the value of depothead.ProjectId
     *
     * @mbggenerated
     */
    public Long getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.ProjectId
     *
     * @param projectid the value for depothead.ProjectId
     *
     * @mbggenerated
     */
    public void setProjectid(Long projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.DefaultNumber
     *
     * @return the value of depothead.DefaultNumber
     *
     * @mbggenerated
     */
    public String getDefaultnumber() {
        return defaultnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.DefaultNumber
     *
     * @param defaultnumber the value for depothead.DefaultNumber
     *
     * @mbggenerated
     */
    public void setDefaultnumber(String defaultnumber) {
        this.defaultnumber = defaultnumber == null ? null : defaultnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.Number
     *
     * @return the value of depothead.Number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.Number
     *
     * @param number the value for depothead.Number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.OperPersonName
     *
     * @return the value of depothead.OperPersonName
     *
     * @mbggenerated
     */
    public String getOperpersonname() {
        return operpersonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.OperPersonName
     *
     * @param operpersonname the value for depothead.OperPersonName
     *
     * @mbggenerated
     */
    public void setOperpersonname(String operpersonname) {
        this.operpersonname = operpersonname == null ? null : operpersonname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.CreateTime
     *
     * @return the value of depothead.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.CreateTime
     *
     * @param createtime the value for depothead.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.OperTime
     *
     * @return the value of depothead.OperTime
     *
     * @mbggenerated
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.OperTime
     *
     * @param opertime the value for depothead.OperTime
     *
     * @mbggenerated
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.OrganId
     *
     * @return the value of depothead.OrganId
     *
     * @mbggenerated
     */
    public Long getOrganid() {
        return organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.OrganId
     *
     * @param organid the value for depothead.OrganId
     *
     * @mbggenerated
     */
    public void setOrganid(Long organid) {
        this.organid = organid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.HandsPersonId
     *
     * @return the value of depothead.HandsPersonId
     *
     * @mbggenerated
     */
    public Long getHandspersonid() {
        return handspersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.HandsPersonId
     *
     * @param handspersonid the value for depothead.HandsPersonId
     *
     * @mbggenerated
     */
    public void setHandspersonid(Long handspersonid) {
        this.handspersonid = handspersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.AccountId
     *
     * @return the value of depothead.AccountId
     *
     * @mbggenerated
     */
    public Long getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.AccountId
     *
     * @param accountid the value for depothead.AccountId
     *
     * @mbggenerated
     */
    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.ChangeAmount
     *
     * @return the value of depothead.ChangeAmount
     *
     * @mbggenerated
     */
    public BigDecimal getChangeamount() {
        return changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.ChangeAmount
     *
     * @param changeamount the value for depothead.ChangeAmount
     *
     * @mbggenerated
     */
    public void setChangeamount(BigDecimal changeamount) {
        this.changeamount = changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.AllocationProjectId
     *
     * @return the value of depothead.AllocationProjectId
     *
     * @mbggenerated
     */
    public Long getAllocationprojectid() {
        return allocationprojectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.AllocationProjectId
     *
     * @param allocationprojectid the value for depothead.AllocationProjectId
     *
     * @mbggenerated
     */
    public void setAllocationprojectid(Long allocationprojectid) {
        this.allocationprojectid = allocationprojectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.TotalPrice
     *
     * @return the value of depothead.TotalPrice
     *
     * @mbggenerated
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.TotalPrice
     *
     * @param totalprice the value for depothead.TotalPrice
     *
     * @mbggenerated
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.PayType
     *
     * @return the value of depothead.PayType
     *
     * @mbggenerated
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.PayType
     *
     * @param paytype the value for depothead.PayType
     *
     * @mbggenerated
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.Remark
     *
     * @return the value of depothead.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.Remark
     *
     * @param remark the value for depothead.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.Salesman
     *
     * @return the value of depothead.Salesman
     *
     * @mbggenerated
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.Salesman
     *
     * @param salesman the value for depothead.Salesman
     *
     * @mbggenerated
     */
    public void setSalesman(String salesman) {
        this.salesman = salesman == null ? null : salesman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.AccountIdList
     *
     * @return the value of depothead.AccountIdList
     *
     * @mbggenerated
     */
    public String getAccountidlist() {
        return accountidlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.AccountIdList
     *
     * @param accountidlist the value for depothead.AccountIdList
     *
     * @mbggenerated
     */
    public void setAccountidlist(String accountidlist) {
        this.accountidlist = accountidlist == null ? null : accountidlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.AccountMoneyList
     *
     * @return the value of depothead.AccountMoneyList
     *
     * @mbggenerated
     */
    public String getAccountmoneylist() {
        return accountmoneylist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.AccountMoneyList
     *
     * @param accountmoneylist the value for depothead.AccountMoneyList
     *
     * @mbggenerated
     */
    public void setAccountmoneylist(String accountmoneylist) {
        this.accountmoneylist = accountmoneylist == null ? null : accountmoneylist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.Discount
     *
     * @return the value of depothead.Discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.Discount
     *
     * @param discount the value for depothead.Discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.DiscountMoney
     *
     * @return the value of depothead.DiscountMoney
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountmoney() {
        return discountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.DiscountMoney
     *
     * @param discountmoney the value for depothead.DiscountMoney
     *
     * @mbggenerated
     */
    public void setDiscountmoney(BigDecimal discountmoney) {
        this.discountmoney = discountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.DiscountLastMoney
     *
     * @return the value of depothead.DiscountLastMoney
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountlastmoney() {
        return discountlastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.DiscountLastMoney
     *
     * @param discountlastmoney the value for depothead.DiscountLastMoney
     *
     * @mbggenerated
     */
    public void setDiscountlastmoney(BigDecimal discountlastmoney) {
        this.discountlastmoney = discountlastmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.OtherMoney
     *
     * @return the value of depothead.OtherMoney
     *
     * @mbggenerated
     */
    public BigDecimal getOthermoney() {
        return othermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.OtherMoney
     *
     * @param othermoney the value for depothead.OtherMoney
     *
     * @mbggenerated
     */
    public void setOthermoney(BigDecimal othermoney) {
        this.othermoney = othermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.OtherMoneyList
     *
     * @return the value of depothead.OtherMoneyList
     *
     * @mbggenerated
     */
    public String getOthermoneylist() {
        return othermoneylist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.OtherMoneyList
     *
     * @param othermoneylist the value for depothead.OtherMoneyList
     *
     * @mbggenerated
     */
    public void setOthermoneylist(String othermoneylist) {
        this.othermoneylist = othermoneylist == null ? null : othermoneylist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.OtherMoneyItem
     *
     * @return the value of depothead.OtherMoneyItem
     *
     * @mbggenerated
     */
    public String getOthermoneyitem() {
        return othermoneyitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.OtherMoneyItem
     *
     * @param othermoneyitem the value for depothead.OtherMoneyItem
     *
     * @mbggenerated
     */
    public void setOthermoneyitem(String othermoneyitem) {
        this.othermoneyitem = othermoneyitem == null ? null : othermoneyitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.AccountDay
     *
     * @return the value of depothead.AccountDay
     *
     * @mbggenerated
     */
    public Integer getAccountday() {
        return accountday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.AccountDay
     *
     * @param accountday the value for depothead.AccountDay
     *
     * @mbggenerated
     */
    public void setAccountday(Integer accountday) {
        this.accountday = accountday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depothead.Status
     *
     * @return the value of depothead.Status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depothead.Status
     *
     * @param status the value for depothead.Status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}