package com.xue.erp.datasource.entities;

public class Functions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functions.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functions.Number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functions.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functions.PNumber
     *
     * @mbggenerated
     */
    private String pnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functions.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functions.State
     *
     * @mbggenerated
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functions.Sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functions.Enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functions.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column functions.PushBtn
     *
     * @mbggenerated
     */
    private String pushbtn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functions.Id
     *
     * @return the value of functions.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functions.Id
     *
     * @param id the value for functions.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functions.Number
     *
     * @return the value of functions.Number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functions.Number
     *
     * @param number the value for functions.Number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functions.Name
     *
     * @return the value of functions.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functions.Name
     *
     * @param name the value for functions.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functions.PNumber
     *
     * @return the value of functions.PNumber
     *
     * @mbggenerated
     */
    public String getPnumber() {
        return pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functions.PNumber
     *
     * @param pnumber the value for functions.PNumber
     *
     * @mbggenerated
     */
    public void setPnumber(String pnumber) {
        this.pnumber = pnumber == null ? null : pnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functions.URL
     *
     * @return the value of functions.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functions.URL
     *
     * @param url the value for functions.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functions.State
     *
     * @return the value of functions.State
     *
     * @mbggenerated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functions.State
     *
     * @param state the value for functions.State
     *
     * @mbggenerated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functions.Sort
     *
     * @return the value of functions.Sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functions.Sort
     *
     * @param sort the value for functions.Sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functions.Enabled
     *
     * @return the value of functions.Enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functions.Enabled
     *
     * @param enabled the value for functions.Enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functions.Type
     *
     * @return the value of functions.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functions.Type
     *
     * @param type the value for functions.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column functions.PushBtn
     *
     * @return the value of functions.PushBtn
     *
     * @mbggenerated
     */
    public String getPushbtn() {
        return pushbtn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column functions.PushBtn
     *
     * @param pushbtn the value for functions.PushBtn
     *
     * @mbggenerated
     */
    public void setPushbtn(String pushbtn) {
        this.pushbtn = pushbtn == null ? null : pushbtn.trim();
    }
}