package com.xue.erp.datasource.entities;

public class MaterialProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materialproperty.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materialproperty.nativeName
     *
     * @mbggenerated
     */
    private String nativename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materialproperty.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materialproperty.sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materialproperty.anotherName
     *
     * @mbggenerated
     */
    private String anothername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materialproperty.id
     *
     * @return the value of materialproperty.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materialproperty.id
     *
     * @param id the value for materialproperty.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materialproperty.nativeName
     *
     * @return the value of materialproperty.nativeName
     *
     * @mbggenerated
     */
    public String getNativename() {
        return nativename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materialproperty.nativeName
     *
     * @param nativename the value for materialproperty.nativeName
     *
     * @mbggenerated
     */
    public void setNativename(String nativename) {
        this.nativename = nativename == null ? null : nativename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materialproperty.enabled
     *
     * @return the value of materialproperty.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materialproperty.enabled
     *
     * @param enabled the value for materialproperty.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materialproperty.sort
     *
     * @return the value of materialproperty.sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materialproperty.sort
     *
     * @param sort the value for materialproperty.sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materialproperty.anotherName
     *
     * @return the value of materialproperty.anotherName
     *
     * @mbggenerated
     */
    public String getAnothername() {
        return anothername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materialproperty.anotherName
     *
     * @param anothername the value for materialproperty.anotherName
     *
     * @mbggenerated
     */
    public void setAnothername(String anothername) {
        this.anothername = anothername == null ? null : anothername.trim();
    }
}