package com.xue.erp.datasource.entities;

import java.math.BigDecimal;

public class Material {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.CategoryId
     *
     * @mbggenerated
     */
    private Long categoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Mfrs
     *
     * @mbggenerated
     */
    private String mfrs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Packing
     *
     * @mbggenerated
     */
    private BigDecimal packing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.SafetyStock
     *
     * @mbggenerated
     */
    private BigDecimal safetystock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Standard
     *
     * @mbggenerated
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Color
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.RetailPrice
     *
     * @mbggenerated
     */
    private BigDecimal retailprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.LowPrice
     *
     * @mbggenerated
     */
    private BigDecimal lowprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.PresetPriceOne
     *
     * @mbggenerated
     */
    private BigDecimal presetpriceone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.PresetPriceTwo
     *
     * @mbggenerated
     */
    private BigDecimal presetpricetwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.UnitId
     *
     * @mbggenerated
     */
    private Long unitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.FirstOutUnit
     *
     * @mbggenerated
     */
    private String firstoutunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.FirstInUnit
     *
     * @mbggenerated
     */
    private String firstinunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.PriceStrategy
     *
     * @mbggenerated
     */
    private String pricestrategy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.OtherField1
     *
     * @mbggenerated
     */
    private String otherfield1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.OtherField2
     *
     * @mbggenerated
     */
    private String otherfield2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.OtherField3
     *
     * @mbggenerated
     */
    private String otherfield3;
    /**
     * 2019-01-21新增字段enableSerialNumber
     *是否开启序列号
     * */
    private String enableSerialNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Id
     *
     * @return the value of material.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Id
     *
     * @param id the value for material.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.CategoryId
     *
     * @return the value of material.CategoryId
     *
     * @mbggenerated
     */
    public Long getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.CategoryId
     *
     * @param categoryid the value for material.CategoryId
     *
     * @mbggenerated
     */
    public void setCategoryid(Long categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Name
     *
     * @return the value of material.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Name
     *
     * @param name the value for material.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Mfrs
     *
     * @return the value of material.Mfrs
     *
     * @mbggenerated
     */
    public String getMfrs() {
        return mfrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Mfrs
     *
     * @param mfrs the value for material.Mfrs
     *
     * @mbggenerated
     */
    public void setMfrs(String mfrs) {
        this.mfrs = mfrs == null ? null : mfrs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Packing
     *
     * @return the value of material.Packing
     *
     * @mbggenerated
     */
    public BigDecimal getPacking() {
        return packing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Packing
     *
     * @param packing the value for material.Packing
     *
     * @mbggenerated
     */
    public void setPacking(BigDecimal packing) {
        this.packing = packing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.SafetyStock
     *
     * @return the value of material.SafetyStock
     *
     * @mbggenerated
     */
    public BigDecimal getSafetystock() {
        return safetystock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.SafetyStock
     *
     * @param safetystock the value for material.SafetyStock
     *
     * @mbggenerated
     */
    public void setSafetystock(BigDecimal safetystock) {
        this.safetystock = safetystock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Model
     *
     * @return the value of material.Model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Model
     *
     * @param model the value for material.Model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Standard
     *
     * @return the value of material.Standard
     *
     * @mbggenerated
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Standard
     *
     * @param standard the value for material.Standard
     *
     * @mbggenerated
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Color
     *
     * @return the value of material.Color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Color
     *
     * @param color the value for material.Color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Unit
     *
     * @return the value of material.Unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Unit
     *
     * @param unit the value for material.Unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Remark
     *
     * @return the value of material.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Remark
     *
     * @param remark the value for material.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.RetailPrice
     *
     * @return the value of material.RetailPrice
     *
     * @mbggenerated
     */
    public BigDecimal getRetailprice() {
        return retailprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.RetailPrice
     *
     * @param retailprice the value for material.RetailPrice
     *
     * @mbggenerated
     */
    public void setRetailprice(BigDecimal retailprice) {
        this.retailprice = retailprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.LowPrice
     *
     * @return the value of material.LowPrice
     *
     * @mbggenerated
     */
    public BigDecimal getLowprice() {
        return lowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.LowPrice
     *
     * @param lowprice the value for material.LowPrice
     *
     * @mbggenerated
     */
    public void setLowprice(BigDecimal lowprice) {
        this.lowprice = lowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.PresetPriceOne
     *
     * @return the value of material.PresetPriceOne
     *
     * @mbggenerated
     */
    public BigDecimal getPresetpriceone() {
        return presetpriceone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.PresetPriceOne
     *
     * @param presetpriceone the value for material.PresetPriceOne
     *
     * @mbggenerated
     */
    public void setPresetpriceone(BigDecimal presetpriceone) {
        this.presetpriceone = presetpriceone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.PresetPriceTwo
     *
     * @return the value of material.PresetPriceTwo
     *
     * @mbggenerated
     */
    public BigDecimal getPresetpricetwo() {
        return presetpricetwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.PresetPriceTwo
     *
     * @param presetpricetwo the value for material.PresetPriceTwo
     *
     * @mbggenerated
     */
    public void setPresetpricetwo(BigDecimal presetpricetwo) {
        this.presetpricetwo = presetpricetwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.UnitId
     *
     * @return the value of material.UnitId
     *
     * @mbggenerated
     */
    public Long getUnitid() {
        return unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.UnitId
     *
     * @param unitid the value for material.UnitId
     *
     * @mbggenerated
     */
    public void setUnitid(Long unitid) {
        this.unitid = unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.FirstOutUnit
     *
     * @return the value of material.FirstOutUnit
     *
     * @mbggenerated
     */
    public String getFirstoutunit() {
        return firstoutunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.FirstOutUnit
     *
     * @param firstoutunit the value for material.FirstOutUnit
     *
     * @mbggenerated
     */
    public void setFirstoutunit(String firstoutunit) {
        this.firstoutunit = firstoutunit == null ? null : firstoutunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.FirstInUnit
     *
     * @return the value of material.FirstInUnit
     *
     * @mbggenerated
     */
    public String getFirstinunit() {
        return firstinunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.FirstInUnit
     *
     * @param firstinunit the value for material.FirstInUnit
     *
     * @mbggenerated
     */
    public void setFirstinunit(String firstinunit) {
        this.firstinunit = firstinunit == null ? null : firstinunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.PriceStrategy
     *
     * @return the value of material.PriceStrategy
     *
     * @mbggenerated
     */
    public String getPricestrategy() {
        return pricestrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.PriceStrategy
     *
     * @param pricestrategy the value for material.PriceStrategy
     *
     * @mbggenerated
     */
    public void setPricestrategy(String pricestrategy) {
        this.pricestrategy = pricestrategy == null ? null : pricestrategy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Enabled
     *
     * @return the value of material.Enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Enabled
     *
     * @param enabled the value for material.Enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.OtherField1
     *
     * @return the value of material.OtherField1
     *
     * @mbggenerated
     */
    public String getOtherfield1() {
        return otherfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.OtherField1
     *
     * @param otherfield1 the value for material.OtherField1
     *
     * @mbggenerated
     */
    public void setOtherfield1(String otherfield1) {
        this.otherfield1 = otherfield1 == null ? null : otherfield1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.OtherField2
     *
     * @return the value of material.OtherField2
     *
     * @mbggenerated
     */
    public String getOtherfield2() {
        return otherfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.OtherField2
     *
     * @param otherfield2 the value for material.OtherField2
     *
     * @mbggenerated
     */
    public void setOtherfield2(String otherfield2) {
        this.otherfield2 = otherfield2 == null ? null : otherfield2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.OtherField3
     *
     * @return the value of material.OtherField3
     *
     * @mbggenerated
     */
    public String getOtherfield3() {
        return otherfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.OtherField3
     *
     * @param otherfield3 the value for material.OtherField3
     *
     * @mbggenerated
     */
    public void setOtherfield3(String otherfield3) {
        this.otherfield3 = otherfield3 == null ? null : otherfield3.trim();
    }

    public String getEnableSerialNumber() {
        return enableSerialNumber;
    }

    public void setEnableSerialNumber(String enableSerialNumber) {
        this.enableSerialNumber = enableSerialNumber;
    }
}