package com.xue.erp.datasource.entities;

import java.math.BigDecimal;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier
     *
     * @mbggenerated
     */
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contacts
     *
     * @mbggenerated
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.phonenum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.isystem
     *
     * @mbggenerated
     */
    private Byte isystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.AdvanceIn
     *
     * @mbggenerated
     */
    private BigDecimal advancein;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.BeginNeedGet
     *
     * @mbggenerated
     */
    private BigDecimal beginneedget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.BeginNeedPay
     *
     * @mbggenerated
     */
    private BigDecimal beginneedpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.AllNeedGet
     *
     * @mbggenerated
     */
    private BigDecimal allneedget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.AllNeedPay
     *
     * @mbggenerated
     */
    private BigDecimal allneedpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.taxNum
     *
     * @mbggenerated
     */
    private String taxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.bankName
     *
     * @mbggenerated
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.accountNumber
     *
     * @mbggenerated
     */
    private String accountnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.taxRate
     *
     * @mbggenerated
     */
    private BigDecimal taxrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.id
     *
     * @return the value of supplier.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.id
     *
     * @param id the value for supplier.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier
     *
     * @return the value of supplier.supplier
     *
     * @mbggenerated
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier
     *
     * @param supplier the value for supplier.supplier
     *
     * @mbggenerated
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contacts
     *
     * @return the value of supplier.contacts
     *
     * @mbggenerated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contacts
     *
     * @param contacts the value for supplier.contacts
     *
     * @mbggenerated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.phonenum
     *
     * @return the value of supplier.phonenum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.phonenum
     *
     * @param phonenum the value for supplier.phonenum
     *
     * @mbggenerated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.email
     *
     * @return the value of supplier.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.email
     *
     * @param email the value for supplier.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.description
     *
     * @return the value of supplier.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.description
     *
     * @param description the value for supplier.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.isystem
     *
     * @return the value of supplier.isystem
     *
     * @mbggenerated
     */
    public Byte getIsystem() {
        return isystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.isystem
     *
     * @param isystem the value for supplier.isystem
     *
     * @mbggenerated
     */
    public void setIsystem(Byte isystem) {
        this.isystem = isystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.type
     *
     * @return the value of supplier.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.type
     *
     * @param type the value for supplier.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.enabled
     *
     * @return the value of supplier.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.enabled
     *
     * @param enabled the value for supplier.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.AdvanceIn
     *
     * @return the value of supplier.AdvanceIn
     *
     * @mbggenerated
     */
    public BigDecimal getAdvancein() {
        return advancein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.AdvanceIn
     *
     * @param advancein the value for supplier.AdvanceIn
     *
     * @mbggenerated
     */
    public void setAdvancein(BigDecimal advancein) {
        this.advancein = advancein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.BeginNeedGet
     *
     * @return the value of supplier.BeginNeedGet
     *
     * @mbggenerated
     */
    public BigDecimal getBeginneedget() {
        return beginneedget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.BeginNeedGet
     *
     * @param beginneedget the value for supplier.BeginNeedGet
     *
     * @mbggenerated
     */
    public void setBeginneedget(BigDecimal beginneedget) {
        this.beginneedget = beginneedget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.BeginNeedPay
     *
     * @return the value of supplier.BeginNeedPay
     *
     * @mbggenerated
     */
    public BigDecimal getBeginneedpay() {
        return beginneedpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.BeginNeedPay
     *
     * @param beginneedpay the value for supplier.BeginNeedPay
     *
     * @mbggenerated
     */
    public void setBeginneedpay(BigDecimal beginneedpay) {
        this.beginneedpay = beginneedpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.AllNeedGet
     *
     * @return the value of supplier.AllNeedGet
     *
     * @mbggenerated
     */
    public BigDecimal getAllneedget() {
        return allneedget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.AllNeedGet
     *
     * @param allneedget the value for supplier.AllNeedGet
     *
     * @mbggenerated
     */
    public void setAllneedget(BigDecimal allneedget) {
        this.allneedget = allneedget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.AllNeedPay
     *
     * @return the value of supplier.AllNeedPay
     *
     * @mbggenerated
     */
    public BigDecimal getAllneedpay() {
        return allneedpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.AllNeedPay
     *
     * @param allneedpay the value for supplier.AllNeedPay
     *
     * @mbggenerated
     */
    public void setAllneedpay(BigDecimal allneedpay) {
        this.allneedpay = allneedpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.fax
     *
     * @return the value of supplier.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.fax
     *
     * @param fax the value for supplier.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.telephone
     *
     * @return the value of supplier.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.telephone
     *
     * @param telephone the value for supplier.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.address
     *
     * @return the value of supplier.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.address
     *
     * @param address the value for supplier.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.taxNum
     *
     * @return the value of supplier.taxNum
     *
     * @mbggenerated
     */
    public String getTaxnum() {
        return taxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.taxNum
     *
     * @param taxnum the value for supplier.taxNum
     *
     * @mbggenerated
     */
    public void setTaxnum(String taxnum) {
        this.taxnum = taxnum == null ? null : taxnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.bankName
     *
     * @return the value of supplier.bankName
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.bankName
     *
     * @param bankname the value for supplier.bankName
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.accountNumber
     *
     * @return the value of supplier.accountNumber
     *
     * @mbggenerated
     */
    public String getAccountnumber() {
        return accountnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.accountNumber
     *
     * @param accountnumber the value for supplier.accountNumber
     *
     * @mbggenerated
     */
    public void setAccountnumber(String accountnumber) {
        this.accountnumber = accountnumber == null ? null : accountnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.taxRate
     *
     * @return the value of supplier.taxRate
     *
     * @mbggenerated
     */
    public BigDecimal getTaxrate() {
        return taxrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.taxRate
     *
     * @param taxrate the value for supplier.taxRate
     *
     * @mbggenerated
     */
    public void setTaxrate(BigDecimal taxrate) {
        this.taxrate = taxrate;
    }
}