package com.xue.erp.datasource.entities;

public class Unit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.UName
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.id
     *
     * @return the value of unit.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.id
     *
     * @param id the value for unit.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.UName
     *
     * @return the value of unit.UName
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.UName
     *
     * @param uname the value for unit.UName
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }
}