package com.xue.erp.datasource.entities;

public class UserBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbusiness.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbusiness.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbusiness.KeyId
     *
     * @mbggenerated
     */
    private String keyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbusiness.Value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbusiness.BtnStr
     *
     * @mbggenerated
     */
    private String btnstr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbusiness.Id
     *
     * @return the value of userbusiness.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbusiness.Id
     *
     * @param id the value for userbusiness.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbusiness.Type
     *
     * @return the value of userbusiness.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbusiness.Type
     *
     * @param type the value for userbusiness.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbusiness.KeyId
     *
     * @return the value of userbusiness.KeyId
     *
     * @mbggenerated
     */
    public String getKeyid() {
        return keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbusiness.KeyId
     *
     * @param keyid the value for userbusiness.KeyId
     *
     * @mbggenerated
     */
    public void setKeyid(String keyid) {
        this.keyid = keyid == null ? null : keyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbusiness.Value
     *
     * @return the value of userbusiness.Value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbusiness.Value
     *
     * @param value the value for userbusiness.Value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbusiness.BtnStr
     *
     * @return the value of userbusiness.BtnStr
     *
     * @mbggenerated
     */
    public String getBtnstr() {
        return btnstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbusiness.BtnStr
     *
     * @param btnstr the value for userbusiness.BtnStr
     *
     * @mbggenerated
     */
    public void setBtnstr(String btnstr) {
        this.btnstr = btnstr == null ? null : btnstr.trim();
    }
}